ability_refresh: 60
api_key_blue: ahRz1L8vDLLqEXoLgyATODnllghP5JmyTQMjNJO792g
api_key_red: 0dOxdAvaXIe_1o22EtTWAhFNMk5nh27ST26AuFAuRJ8
app.contact.dns.domain: caldera.lab
app.contact.dns.socket: 0.0.0.0:53
app.contact.ftp.host: 0.0.0.0
app.contact.ftp.port: 21
app.contact.ftp.pword: caldera
app.contact.ftp.server.dir: ftp_dir
app.contact.ftp.user: caldera_user
app.contact.gist: API_KEY
app.contact.html: /weather
app.contact.http: http://0.0.0.0:80
app.contact.slack.api_key: SLACK_TOKEN
app.contact.slack.bot_id: SLACK_BOT_ID
app.contact.slack.channel_id: SLACK_CHANNEL_ID
app.contact.tcp: 0.0.0.0:7010
app.contact.tunnel.ssh.host_key_file: REPLACE_WITH_KEY_FILE_PATH
app.contact.tunnel.ssh.host_key_passphrase: REPLACE_WITH_KEY_FILE_PASSPHRASE
app.contact.tunnel.ssh.socket: 0.0.0.0:22
app.contact.tunnel.ssh.user_name: sandcat
app.contact.tunnel.ssh.user_password: s4ndc4t!
app.contact.udp: 0.0.0.0:7011
app.contact.websocket: 0.0.0.0:7012
auth.login.handler.module: default
crypt_salt: EYlwl8kyiDpRr2fYBuBErjj_oRzSGSlUbDSavH1tpzI
encryption_key: QfMsdeUN5KeWsOdbzIKW_WdS5eewoWNNsJIHv8Gomh4
exfil_dir: /tmp/caldera
host: 0.0.0.0
objects.planners.default: atomic
plugins:
- access
- atomic
- compass
- debrief
- emu
- fieldmanual
- manx
- response
- sandcat
- stockpile
- training
port: 80
reports_dir: /tmp
requirements:
  go:
    command: go version
    type: installed_program
    version: 1.19
  python:
    attr: version
    module: sys
    type: python_module
    version: 3.8.0
users:
  blue:
    blue: calderapassword
  red:
    red: calderapassword
