version: '3.8'
services:
  infectionmonkey:
    hostname: infectionmonkey.lab
    build:
      context: .
      dockerfile: build/infectionmonkey.Dockerfile
    image: 'csalab/csaf-infectionmonkey:latest'
    restart: always
    volumes:
      - infectionmonkey:/opt/infectionmonkey
    networks:
      attack:
        ipv4_address: 10.0.0.110
      defense:
        ipv4_address: 10.0.1.110

  mongodb:
    image: 'mongo:7.0.4-rc0'
    hostname: mongodb.lab
    restart: always
    volumes:
      - mongodb_db:/data/db
      - mongodb_configdb:/data/configdb
    networks:
      attack:
        ipv4_address: 10.0.0.111

  purpleops:
    hostname: purpleops.lab
    build:
      context: .
      dockerfile: build/purpleops.Dockerfile
    image: 'csalab/csaf-purpleops:latest'
    restart: always
    command: gunicorn --bind 0.0.0.0:80 purpleops:app
    environment:
      - MONGO_DB=purpleops
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - FLASK_DEBUG=True
      - FLASK_MFA=False
      - HOST=0.0.0.0
      - PORT=80
      - NAME=csaf
    depends_on:
      - mongodb
    volumes:
      - purpleops:/usr/src/app
    networks:
      attack:
        ipv4_address: 10.0.0.112
      defense:
        ipv4_address: 10.0.1.112

  caldera:
    hostname: caldera.lab
    build:
      context: .
      dockerfile: build/caldera.Dockerfile
    image: csalab/csaf-caldera:latest
    restart: always
    volumes:
      - ./config/caldera/local.yml:/usr/src/app/conf/local.yml
      - caldera:/usr/src/app
    networks:
      attack:
        ipv4_address: 10.0.0.113
      defense:
        ipv4_address: 10.0.1.113

networks:
  attack:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1

  defense:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 10.0.1.0/24
          gateway: 10.0.1.1

volumes:
  infectionmonkey: {}
  purpleops: {}
  mongodb_db: {}
  mongodb_configdb: {}
  caldera: {}
