version: '3.8'
services:
  attack:
    hostname: attack.lab
    build:
      context: .
      dockerfile: build/kalilinux.Dockerfile
    image: 'csalab/csaf-kali:latest'
    restart: always
    ports:
      - 0.0.0.0:6080:8080
    environment:
      - SHELL=/bin/bash
      - VNC_PASSWORD=${ATTACK_PASS:-attack}
    networks:
      attack:
        ipv4_address: 10.0.0.100
      internal:
        ipv4_address: 10.0.5.100

  phising:
    hostname: phising.lab
    image: 'csalab/csaf-phising:latest'
    build:
      context: .
      dockerfile: build/phising.Dockerfile
    restart: always
    environment:
      - WEBSITE=${PHISING_WEB:-https://gmail.com/}
    networks:
      attack:
        ipv4_address: 10.0.0.200
    
  server.lab:
    hostname: mail.server.lab
    image: 'iredmail/mariadb:stable'
    restart: always
    environment:
      - HOSTNAME=mail.server.lab
      - FIRST_MAIL_DOMAIN=server.lab
      - FIRST_MAIL_DOMAIN_ADMIN_PASSWORD=${MAIL_PASS:-supersecretpassword}
      - MLMMJADMIN_API_TOKEN=CCmMymMpFH35K8Q0H3FQAsSRQzkSjCeazm+t1X27cdE=
      - ROUNDCUBE_DES_KEY=s9lVEEaiA+MmvYZvfi1k0WQNFiFmGOYI
    volumes:
      - iredmail_backup-mysql:/var/vmail/backup/mysql
      - iredmail_mailboxes:/var/vmail/vmail1
      - iredmail_mlmmj:/var/vmail/mlmmj
      - iredmail_mlmmj_archive:/var/vmail/mlmmj-archive
      - iredmail_imapsieve_copy:/var/vmail/imapsieve_copy
      - iredmail_custom:/opt/iredmail/custom
      - iredmail_ssl:/opt/iredmail/ssl
      - iredmail_mysql:/var/lib/mysql
      - iredmail_clamav:/var/lib/clamav
      - iredmail_sa_rules:/var/lib/spamassassin
      - iredmail_postfix_queue:/var/spool/postfix
    networks:
      attack:
        ipv4_address: 10.0.0.201

  gophish:
    image: 'gophish/gophish:latest'
    hostname: gophish.lab
    restart: always
    environment:
      - GOPHISH_INITIAL_ADMIN_PASSWORD=${GOPHISH_PASS:-gophishpassword}
    networks:
      attack:
        ipv4_address: 10.0.0.202

networks:
  attack:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/24
          gateway: 10.0.0.1

  internal:
    driver: bridge
    internal: true
    ipam:
      config:
        - subnet: 10.0.5.0/24
          gateway: 10.0.5.1

volumes:
  iredmail_backup-mysql: {}
  iredmail_mailboxes: {}
  iredmail_mlmmj: {}
  iredmail_mlmmj_archive: {}
  iredmail_imapsieve_copy: {}
  iredmail_custom: {}
  iredmail_ssl: {}
  iredmail_mysql: {}
  iredmail_clamav: {}
  iredmail_sa_rules: {}
  iredmail_postfix_queue: {}
