#!/bin/sh
### BEGIN INIT INFO
# Provides:          velociraptor-client
# Required-Start:    $network
# Required-Stop:     $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Velociraptor Client Agent
# Description:       Velociraptor DFIR endpoint agent
### END INIT INFO

DAEMON="/usr/local/bin/velociraptor"
DAEMON_ARGS="--config /etc/velociraptor-client.config.yaml client -v"
PIDFILE="/var/run/velociraptor-client.pid"
LOGFILE="/var/log/velociraptor-client.log"
USER="root"

start() {
    echo "Starting Velociraptor Client..."
    start-stop-daemon --start --background \
        --make-pidfile --pidfile $PIDFILE \
        --chuid $USER \
        --exec $DAEMON -- $DAEMON_ARGS >> $LOGFILE 2>&1
    echo "Velociraptor Client started."
}

stop() {
    echo "Stopping Velociraptor Client..."
    start-stop-daemon --stop --pidfile $PIDFILE
    rm -f $PIDFILE
    echo "Velociraptor Client stopped."
}

restart() {
    stop
    sleep 2
    start
}

status() {
    if [ -f "$PIDFILE" ] && kill -0 "$(cat $PIDFILE)" 2>/dev/null; then
        echo "Velociraptor Client is running (PID $(cat $PIDFILE))"
        return 0
    else
        echo "Velociraptor Client is NOT running"
        return 1
    fi
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    status)
        status
        ;;
    *)
        echo "Usage: /etc/init.d/velociraptor-client {start|stop|restart|status}"
        exit 1
        ;;
esac

exit 0
