groups:
- name: monitor
  rules:
  - alert: monitor_service_down
    expr: up == 0
    for: 10s
    labels:
      severity: critical
    annotations:
      summary: "Monitor service non-operational"
      description: "Service {{ $labels.instance }} is down."

- name: host
  rules:
  - alert: high_cpu_load
    expr: node_load1 > 10
    for: 10s
    labels:
      severity: warning
    annotations:
      summary: "Server under high load"
      description: "Docker host is under high load, the avg load 1m is at {{ $value}}. Reported by instance {{ $labels.instance }} of job {{ $labels.job }}."

  - alert: high_memory_load
    expr: (sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes) ) / sum(node_memory_MemTotal_bytes) * 100 > 85
    for: 10s
    labels:
      severity: warning
    annotations:
      summary: "Server memory is almost full"
      description: "Docker host memory usage is {{ humanize $value}}%. Reported by instance {{ $labels.instance }} of job {{ $labels.job }}."

  - alert: high_storage_load
    expr: (node_filesystem_size_bytes{fstype="aufs"} - node_filesystem_free_bytes{fstype="aufs"}) / node_filesystem_size_bytes{fstype="aufs"}  * 100 > 85
    for: 10s
    labels:
      severity: warning
    annotations:
      summary: "Server storage is almost full"
      description: "Docker host storage usage is {{ humanize $value}}%. Reported by instance {{ $labels.instance }} of job {{ $labels.job }}."

- name: containers
  rules:
  - alert: mail_down
    expr: absent(container_memory_usage_bytes{name="csaf-docker_server.lab_1"})
    for: 10s
    labels:
      severity: critical
    annotations:
      summary: "Mail down"
      description: "Mail container is down for more than 10 seconds."

  - alert: gitea_down
    expr: absent(container_memory_usage_bytes{name="csaf-docker_gitea_1"})
    for: 10s
    labels:
      severity: critical
    annotations:
      summary: "Gitea down"
      description: "Gitea container is down for more than 10 seconds."

- name: containers_high_cpu
  rules:
  - alert: mail_high_cpu
    expr: sum(rate(container_cpu_usage_seconds_total{name="csaf-docker_server.lab_1"}[1m])) / count(node_cpu_seconds_total{mode="system"}) * 100 > 10
    for: 10s
    labels:
      severity: warning
    annotations:
      summary: "Mail container high CPU usage"
      description: "Mail container CPU usage is {{ humanize $value}}%."

  - alert: gitea_high_cpu
    expr: sum(rate(container_cpu_usage_seconds_total{name="csaf-docker_gitea_1"}[1m])) / count(node_cpu_seconds_total{mode="system"}) * 100 > 10
    for: 10s
    labels:
      severity: warning
    annotations:
      summary: "Gitea container high CPU usage"
      description: "Gitea container CPU usage is {{ humanize $value}}%."

- name: containers_high_memory
  rules:
  - alert: mail_high_memory
    expr: sum(container_memory_usage_bytes{name="csaf-docker_server.lab_1"}) > 3000000000
    for: 10s
    labels:
      severity: warning
    annotations:
      summary: "Mail container high memory usage"
      description: "Mail container memory consumption is at {{ humanize $value}}."

  - alert: gitea_high_memory
    expr: sum(container_memory_usage_bytes{name="csaf-docker_gitea_1"}) > 1200000000
    for: 10s
    labels:
      severity: warning
    annotations:
      summary: "Gitea container high memory usage"
      description: "Gitea container memory consumption is at {{ humanize $value}}."
