global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 10s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager.lab:9093

rule_files:
  - "alert.yml"

scrape_configs:
  - job_name: "prometheus"
    scrape_interval: 10s
    static_configs:
      - targets: ["prometheus.lab:9090"]

  - job_name: 'node-exporter'
    scrape_interval: 10s
    static_configs:
      - targets: ['node-exporter.lab:9100']

  - job_name: 'cadvisor'
    scrape_interval: 10s
    static_configs:
      - targets: ['cadvisor.lab:8080']
