concurrent = 1
check_interval = 0
shutdown_timeout = 0

[session_server]
  session_timeout = 1800

[[runners]]
  name = "runner.gitlab.lab"
  url = "http://gitlab.lab/"
  id = 1
  token = "e8Twh8aydWxxkCawz5gB"
  token_obtained_at = 2023-09-02T17:06:41Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "ubuntu:22.04"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    extra_hosts = ["gitlab.lab:10.0.1.29"]
    shm_size = 0

[[runners]]
  name = "runner.gitlab.lab"
  url = "http://gitlab.lab/"
  id = 2
  token = "USszZ5vwPnxRLyBWGyu9"
  token_obtained_at = 2023-09-03T05:54:30Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.docker]
    tls_verify = false
    image = "ubuntu:22.04"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    extra_hosts = ["gitlab.lab:10.0.1.29"]
    shm_size = 0

[[runners]]
  name = "runner.gitlab.lab"
  url = "http://gitlab.lab"
  id = 3
  token = "glrt-EeNJGjU6zPv45xRRT2Sm"
  token_obtained_at = 2023-09-03T11:06:38Z
  token_expires_at = 0001-01-01T00:00:00Z
  executor = "docker"
  [runners.cache]
    MaxUploadedArchiveSize = 0
  [runners.docker]
    tls_verify = false
    image = "ubuntu:22.04"
    privileged = false
    disable_entrypoint_overwrite = false
    oom_kill_disable = false
    disable_cache = false
    volumes = ["/cache"]
    extra_hosts = ["gitlab.lab:10.0.1.29"]
    shm_size = 0
